menu:
- {name: 'Home', url: '/'}
- {name: 'Research', url: '/research'}
- {name: 'Publications', url: '/publications'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

research:
- {title: 'The magnetic fields in the Milky Way', description: 'To be added...', image: 'assets/img/planck_dust_pol.jpg', url: 'mw_bfield'}

social:
- {icon: 'github', link: 'https://github.com/jackieykma'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0003-0742-2006'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/yik-ki-jackie-ma-a95018b2/'}

contacts:
- {name: 'Dr. Yik Ki (Jackie) Ma', title: 'Postdoctoral Researcher', department: 'Research School of Astronomy & Astrophysics', institution: 'Australian National University', institution_address: 'Canberra, ACT 2611, Australia', host: '(Currently hosted by MPIfR, Bonn, Germany)', phone: '+49 228-525-152', email: 'yikki.ma[at]anu.edu.au', office: '', image: 'assets/img/portrait.jpg'}
